# Leptos 配置文件

# 输出名称
output-name = "server"

# 站点地址
site-addr = "127.0.0.1:3000"

# 重载端口
reload-port = 3001

# 站点根目录
site-root = "target/site"

# 站点包目录
site-pkg-dir = "pkg"

# 样式文件
style-file = "style/main.css"

# 资源目录
assets-dir = "public"

# 浏览器查询
browserquery = "defaults"

# 环境变量
env = "DEV"

# Tailwind 输入文件
tailwind-input-file = "style/main.css"

# Tailwind 配置文件
tailwind-config-file = "tailwind.config.js"
